# Generated by Django 4.1.4 on 2022-12-25 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tour_name', models.CharField(max_length=256)),
                ('tour_date', models.DateTimeField()),
                ('tour_admission', models.BooleanField()),
                ('tour_price', models.FloatField(default=0)),
                ('exhibitions', models.ManyToManyField(to='museum.exhibition')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museum.tour')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('quantity', models.IntegerField()),
                ('in_exhibition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='museum.exhibition')),
            ],
        ),
        migrations.AddField(
            model_name='exhibition',
            name='items',
            field=models.ManyToManyField(to='museum.item'),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='tours',
            field=models.ManyToManyField(to='museum.tour'),
        ),
    ]
