# Generated by Django 4.1.4 on 2022-12-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0002_alter_tour_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='tours',
            field=models.ManyToManyField(null=True, to='museum.tour'),
        ),
    ]
