# Generated by Django 4.1.4 on 2022-12-25 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0003_alter_exhibition_tours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='in_exhibition',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='museum.exhibition'),
        ),
    ]
