# Generated by Django 4.1.4 on 2022-12-25 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0004_alter_item_in_exhibition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='tours',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='museum.tour'),
        ),
        migrations.AlterField(
            model_name='item',
            name='in_exhibition',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='museum.exhibition'),
        ),
    ]
